### ISSUE TITLE
No callImmediately: version of -rz_addTarget:action:forKeyPathChanges:

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/RZDataBinding#22]
I think this method should have a variant that takes `callImmediately` parameter, like its single-key-path cousin.

**Comment by jvisenti** [comment]
@ZevEisenberg The reason it doesn't is because it's not clear which parameters would be in the change dictionary. It would be pretty annoying if it was called once per key path, but if it's called just once then which key path is in the change dictionary? Perhaps none, but that the docs claim that a key path is always included.

**Comment by ZevEisenberg** [comment]
Hadn't thought of that, since I've been using exclusively callbacks without a change dictionary. Dictionary could contain a set/array of changes or something like that, if it doesn't over-complicate things (I bet it would, though).

**Comment by jvisenti** [comment]
Yeah normally this flavor of `rz_addTarget` is used without a change dict, which is why it's pretty straightforward to just call the method yourself after adding the target. But I agree it's weird. A set/array of changes would be complicated indeed :disappointed:

**Comment by jvisenti** [comment]
@ZevEisenberg :skull: For 2.0 I'd like to add a `callImmediately:` parameter. If `NO`, current behavior. If `YES`, call method once for each key path, with the appropriate change dict. If the method doesn't take a change dict parameter, only call the method once.

Do you agree with this proposed change?

**Comment by ZevEisenberg** [comment]
Yes, as long as it's well documented.
