### ISSUE TITLE
Swizzling dealloc is, well, terrifying

### ISSUE THREAD

**Issue by ndonald2** [Raizlabs/RZDataBinding#5]
I am super stoked about this library. Data binding is something that is sorely missing from Cocoa and I am thrilled that RZ is putting this out there.

That said, swizzling dealloc sort of scares me. I see why it's being done, and it's good that you made it optional via the preprocessor, but at the same time I think it should be strongly discouraged for production apps.

Is there any other way to clean up observers besides subclassing or swizzling dealloc for all NSObjects?

**Comment by jkaufman** [comment]
Could we set an associated object on the observed object and unregister the observer from within this object's dealloc?

**Comment by jkaufman** [comment]
Well, never mind, that's what I get for being clever. You already do!

**Comment by ndonald2** [comment]
@jkaufman I have tried that approach in the past but have never been too successful. From a bit of digging it looks like [dealloc order](http://stackoverflow.com/a/10843510) unfortunately does not permit such an approach, as the exception for deallocation with observers still attached will be thrown before the associated object is deallocated and has a chance to clean up.

**Comment by jvisenti** [comment]
@jkaufman @ndonald2 I too tried an associated object approached and it worked perfectly fine. Until we turned on compiler optimizations, thus changing dealloc order. 

After experimenting with several approaches, swizzling dealloc was the most reliable, and we indeed use it in a production app. I realize swizzling dealloc is discouraged, but so is swizzling in general. The convenience and safety that comes with not needing to worry about observation info leak crashes may in this case justify the approach.

**Comment by ndonald2** [comment]
@jvisenti Interesting, I have had issues with dealloc order even without optimizations turned on. I hear what you're saying but I consider it an *enormous* red flag that the compiler does not let you even use `dealloc` in a `@selector()` directly and you have to construct it from a string - that seems like asking for trouble.

I don't disagree that automated cleanup is a wonderful thing, but I might play devil's advocate and say that using binding and KVO willy-nilly without worrying about ownership or memory management can lead to complacency, and a total mess if things were to ever go wrong.

**Comment by jvisenti** [comment]
@ndonald2 The `@selector()` limitation is almost certainly to prevent us from calling dealloc directly under ARC. The same restriction is on `release` and `retain` for instance. As long as we don't change how/when these methods are called it shouldn't be any more dangerous to swizzle than any other method.

There is definitely something to be said for making people really *think* about their use of KVO by requiring cleanup. Perhaps the preprocessor flag could be off by default, but there were two primary reasons I felt automatic cleanup was necessary for this library:

- We ran into a situation where it would have been very difficult to restructure things to have the observer maintain a strong reference to the observed object. Fundamentally, an object shouldn't need ownership of something to observe it.

- It's sketchy *who* should cleanup observers in a property binding situation. Object A binds one of their properties to Object B. Object A can easily break the binding in their own dealloc, but what about Object B? It doesn't even know it's being observed, but if it gets deallocated before Object A there will be a crash. It's also possible that a different observation architecture could solve this problem.

I'd really like suggestions and improvements in this area, because I agree that swizzling dealloc is highly unconventional, but I think automatic cleanup adds enough utility that it should be in there in some form.

**Comment by jkaufman** [comment]
Indeed, associated objects [cannot be used](https://www.mikeash.com/pyblog/friday-qa-2012-03-02-key-value-observing-done-right-take-2.html#comment-beda1cef6fce362a0bd5265df76a4310) in this situation. Now I know.

**Comment by ndonald2** [comment]
Looks like [RAC swizzles dealloc](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/NSObject%2BRACDeallocating.m) as well, per-class being observed. Makes me feel *slightly* better about it but it's still a bit scary. I'll close this issue.
