### ISSUE TITLE
Blocks support needed

### ISSUE THREAD

**Issue by zackhsuan** [Raizlabs/RZDataBinding#52]
Thank you for your great work! 
Is it possible to convert action-target usage to blocks?

**Comment by jvisenti** [comment]
Hi @zackhsuan, the library explicitly doesn't provide support for blocks for two reasons:

1. Block-based KVO invariably leads to memory management issues if you're not very careful, and these issues are hard to track down

2. If you add a block-based observer, it becomes impossible to selectively unregister actions. This is because there is no way to compare blocks the than pointer equality. A solution for this would be to return some handle on the observer, which can be used to unregister later. See the NSNotificationCenter `addObserverForName: object: queue: usingBlock:` API for reference. Currently the observer object is an implementation detail, and I'd rather not leak that in the public interface.

Happy to discuss more details of the decision to not support a block API, but I'm closing this issue for now
